export default `\
# OSV Security CLI — project configuration
# Generated by: osv-security init
# Documentation: https://github.com/google/osv-scanner
#
# protected_packages: packages that must NEVER be auto-upgraded beyond their stated constraint.
#   Any update requiring a constraint change needs explicit per-package authorization.
# safe_update_policy: patch/minor updates within existing constraints are auto-safe.

project:
  name: '{{projectName}}'
  client: '{{client}}'

runtime:
  {{#if hasPhp}}
  php: '{{phpVersion}}'
  {{/if}}
  {{#if hasNpm}}
  node: '{{nodeVersion}}'
  {{/if}}
  execution: '{{execution}}'
  docker_service: '{{dockerService}}'{{#if dockerWorkdir}}
  docker_workdir: '{{dockerWorkdir}}'{{/if}}
  {{#if hasPhp}}
  test_command: '{{testCommand}}'
  {{/if}}
  {{#if hasNpm}}
  build_commands:
    frontend: '{{frontendBuild}}'
    backend: '{{backendBuild}}'
  {{/if}}

# Add packages that must not be auto-upgraded beyond their constraint.
protected_packages:
  {{#if hasPhp}}
  composer:
    []
    # - package: 'vendor/package'
    #   constraint: '^2.0'
    #   reason: 'Major upgrade requires project-wide migration'
  {{else}}
  composer: []
  {{/if}}
  {{#if hasNpm}}
  npm:
    []
    # - package: 'some-package'
    #   constraint: '^3.0.0'
    #   reason: 'v4 has breaking API changes'
  {{else}}
  npm: []
  {{/if}}

safe_update_policy:
  allow_patch_and_minor_within_constraints: true
  require_authorization_for_constraint_change: true
  authorization_format: '{{authorizationFormat}}'

conflict_resolution: 'stop_and_ask'

report_language: '{{reportLanguage}}'

# reports_dir: '.osv-scanner/reports'  # optional — local output directory for reports (default shown)

# cloud_storage:                         # optional — upload reports to cloud storage after generation
#   provider: google_drive
#   folder_id: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'
#   credentials: '.osv-scanner/gdrive-service-account.json'
#   # credentials_env: GDRIVE_SERVICE_ACCOUNT_JSON  # alternative: env var with JSON (for CI/CD)
`;
