export interface GenerateConfigOptions {
  projectName?: string;
  client?: string;
  execution?: 'docker' | 'local';
  dockerService?: string;
  dockerWorkdir?: string;
  phpVersion?: string;
  laravelVersion?: string;
  nodeVersion?: string;
  testCommand?: string;
  frontendBuildCommand?: string;
  backendBuildCommand?: string;
}

export function generateConfigYaml(opts: GenerateConfigOptions = {}): string {
  const projectName = opts.projectName ?? 'My Laravel Project';
  const client = opts.client ?? 'Client Name';
  const execution = opts.execution ?? 'docker';
  const dockerService = opts.dockerService ?? 'app';
  const dockerWorkdir = opts.dockerWorkdir;
  const phpVersion = opts.phpVersion ?? '8.2';
  const laravelVersion = opts.laravelVersion ?? '10.x';
  const nodeVersion = opts.nodeVersion ?? '20.x';
  const testCommand = opts.testCommand ?? 'php artisan test --compact';
  const frontendBuild = opts.frontendBuildCommand ?? 'npm run development-frontend';
  const backendBuild = opts.backendBuildCommand ?? 'npm run development-backend';

  const workdirLine = dockerWorkdir ? `\n  docker_workdir: '${dockerWorkdir}'` : '';

  return `# OSV Security CLI — project configuration
# Generated by: osv-security init
# Documentation: https://github.com/google/osv-scanner
#
# protected_packages: packages that must NEVER be auto-upgraded beyond their stated constraint.
#   Any update requiring a constraint change needs explicit per-package authorization.
# safe_update_policy: patch/minor updates within existing constraints are auto-safe.

project:
  name: '${projectName}'
  client: '${client}'

runtime:
  php: '${phpVersion}'
  laravel: '${laravelVersion}'
  node: '${nodeVersion}'
  package_manager_php: 'composer'
  package_manager_js: 'npm'
  execution: '${execution}'
  docker_service: '${dockerService}'${workdirLine}
  test_command: '${testCommand}'
  build_commands:
    frontend: '${frontendBuild}'
    backend: '${backendBuild}'

# Add packages that must not be auto-upgraded beyond their constraint.
# Examples:
#   composer:
#     - package: 'laravel/framework'
#       constraint: '^10.0'
#       reason: 'Major upgrade to Laravel 11 requires a dedicated project'
#   npm:
#     - package: 'tailwindcss'
#       constraint: '^3.3.3'
#       reason: 'Tailwind v4 has breaking config changes'
protected_packages:
  composer: []
  npm: []

safe_update_policy:
  allow_patch_and_minor_within_constraints: true
  require_authorization_for_constraint_change: true
  authorization_format: 'sim, confirmo breaking changes para [vendor/pacote]'

conflict_resolution: 'stop_and_ask'
`;
}
